language: android
sudo: false
branches:
    only:
        - master
        - devel
env:
    - TERM=dumb

jdk: oraclejdk8

android:
    components:
        - tools
        - build-tools-24.0.2
        - android-24
        - extra-android-m2repository

after_success: ./gradlew jacocoTestReport coveralls
