# Site settings
title: Rectball
email: danirod@outlook.com
description: Rectball is a free puzzle game for Windows, Linux, MacOS X and Android.
baseurl: /rectball
url: http://www.danirod.es

twitter_username: danirod93
github_username:  danirod

# Build settings
markdown: kramdown
